/*
 * Copyright (C) 2026 Alberto Lirussi
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package com.codingful.carve.reporter;

import java.time.LocalDate;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * The provenance note embedded in every generated report file (JSON, DOT,
 * GEXF, HTML): which tool produced the report, when, and under what terms the
 * <em>tool</em> is licensed — plus a no-warranty disclaimer.
 *
 * <p>The note is framed as attribution, not as a copyright claim over the
 * report: the report analyses the user's own code, so the tool's author does
 * not own it, and the tool's AGPL licence governs carve itself, not the
 * generated output. The field names ({@code tool*}) keep that boundary explicit.
 */
final class ReportMetadata {

    private ReportMetadata() { }

    static final String TOOL_NAME         = "carve";
    static final String TOOL_AUTHOR       = "Alberto Lirussi, Codingful.com";
    static final String TOOL_LICENSE_SPDX = "AGPL-3.0-or-later";
    static final String TOOL_LICENSE_URL  = "https://www.gnu.org/licenses/agpl-3.0.html";
    static final String TOOL_REPOSITORY   = "https://github.com/alirux/carve";

    static final String DISCLAIMER =
        "This report is provided \"as is\", with no warranty that its findings are accurate, "
        + "complete, or fit for any particular purpose. The authors accept no liability for any "
        + "damage or loss arising from the use of this report, from reliance on it, or from any "
        + "decision not to use it.";

    static LocalDate generatedOn() {
        return LocalDate.now();
    }

    /** The carve build version, read from the jar manifest; falls back when run unpackaged (tests, IDE). */
    static String version() {
        String v = ReportMetadata.class.getPackage().getImplementationVersion();
        return v != null ? v : "dev-SNAPSHOT";
    }

    static String generatedByLine() {
        return "Generated by " + TOOL_NAME + " v" + version() + " on " + generatedOn() + ".";
    }

    /** Attribution for the tool itself — its copyright and licence, not the report's. */
    static String toolCreditLine() {
        return TOOL_NAME + " is Copyright (C) " + generatedOn().getYear() + " " + TOOL_AUTHOR
            + ", licensed under the GNU Affero General Public License v3.0 or later (" + TOOL_LICENSE_URL + ")."
            + " Source: " + TOOL_REPOSITORY + ".";
    }

    private static List<String> lines() {
        return List.of(generatedByLine(), toolCreditLine(), DISCLAIMER);
    }

    /** The full note as a single HTML/XML comment block. */
    static String asXmlComment() {
        return "<!--\n  " + String.join("\n  ", lines()) + "\n-->";
    }

    /** The full note as {@code //}-style line comments, e.g. for DOT. */
    static String asLineComment() {
        return lines().stream().map(l -> "// " + l).collect(Collectors.joining("\n"));
    }

    /** The note as a field map, for embedding in structured output (JSON report, HTML report data). */
    static Map<String, Object> asMap() {
        var map = new LinkedHashMap<String, Object>();
        map.put("generatedBy",    TOOL_NAME);
        map.put("version",        version());
        map.put("generatedOn",    generatedOn().toString());
        map.put("toolCopyright",  "Copyright (C) " + generatedOn().getYear() + " " + TOOL_AUTHOR);
        map.put("toolLicense",    TOOL_LICENSE_SPDX);
        map.put("toolLicenseUrl", TOOL_LICENSE_URL);
        map.put("toolRepository", TOOL_REPOSITORY);
        map.put("disclaimer",     DISCLAIMER);
        return map;
    }
}
